# Generated by Django 5.2.1 on 2025-06-02 00:39

import django.utils.timezone
from django.db import migrations, models
from django.db.models.deletion import CASCADE


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True)),
                ('password', models.CharField(default='pbkdf2_sha256$600000$changeme', max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, to='auth.permission')),
            ],
            options={
                'db_table': 'clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(max_length=50)),
                ('stock', models.IntegerField(default=0)),
                ('fecha_agregado', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clave',
            fields=[
                ('id', models.AutoField(primary_key=True)),
                ('clave', models.CharField(max_length=255)),
                ('estado', models.CharField(default='disponible', max_length=20)),
                ('fecha_agregado', models.DateTimeField(default=django.utils.timezone.now)),
                ('producto', models.ForeignKey(db_column='producto_id', on_delete=CASCADE, to='api.producto')),
            ],
            options={
                'db_table': 'claves',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(primary_key=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.ForeignKey(db_column='cliente_id', on_delete=CASCADE, to='api.cliente')),
            ],
            options={
                'db_table': 'ventas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.AutoField(primary_key=True)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('venta', models.ForeignKey(db_column='venta_id', on_delete=CASCADE, to='api.venta')),
                ('producto', models.ForeignKey(db_column='producto_id', on_delete=CASCADE, to='api.producto')),
            ],
            options={
                'db_table': 'detalle_ventas',
                'managed': False,
            },
        ),
    ]
