# Generated by Django 5.2.1 on 2025-06-02 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_pago'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'managed': True},
        ),
    ]
